version: "3.8"

services:
  nginx:
    image: nginx
    container_name: "nginx_cont"
    ports:
      - "80:80"
    depends_on:
      - django_app
    networks:
      - notes-app-nw

  django_app:
    image: saud4545/notes-app
    container_name: "notes-app"
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    env_file:
      - ".env"
    depends_on:
      - db
    networks:
      - notes-app-nw

  db:
    image: mysql
    container_name: "db_cont"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    networks:
      - notes-app-nw

networks:
  notes-app-nw:
